/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/reference": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Reference */
    get: operations["reference_api_reference_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/experiment-catalog": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Experiment Catalog */
    get: operations["experiment_catalog_api_experiment_catalog_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/experiment-catalog/{experiment_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Catalog Detail */
    get: operations["catalog_detail_api_experiment_catalog__experiment_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/experiment-catalog/{experiment_id}/evidence/{index}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Catalog Evidence */
    get: operations["catalog_evidence_api_experiment_catalog__experiment_id__evidence__index__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/experiment-catalog/{experiment_id}/owner": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Catalog Owner */
    get: operations["catalog_owner_api_experiment_catalog__experiment_id__owner_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/experiments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Experiments */
    get: operations["experiments_api_experiments_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/experiments/{run_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Detail */
    get: operations["detail_api_experiments__run_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/experiments/{run_id}/bundle": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Bundle */
    get: operations["bundle_api_experiments__run_id__bundle_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/experiments/{run_id}/units/{unit_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Unit */
    get: operations["unit_api_experiments__run_id__units__unit_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/experiments/{run_id}/traces/{trace_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Trace */
    get: operations["trace_api_experiments__run_id__traces__trace_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/experiments/{run_id}/export": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Export */
    get: operations["export_api_experiments__run_id__export_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/experiments/{run_id}/evidence/{reference}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Evidence */
    get: operations["evidence_api_experiments__run_id__evidence__reference__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/trace-jobs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Statuses */
    get: operations["statuses_api_trace_jobs_get"];
    put?: never;
    /** Start */
    post: operations["start_api_trace_jobs_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/trace-jobs/{job_id}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Cancel */
    post: operations["cancel_api_trace_jobs__job_id__cancel_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/collections": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Collections */
    get: operations["collections_api_collections_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/collections/{collection_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** View */
    get: operations["view_api_collections__collection_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/collections/{collection_id}/quality": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Quality */
    get: operations["quality_api_collections__collection_id__quality_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/collections/{collection_id}/games/{game_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Game */
    get: operations["game_api_collections__collection_id__games__game_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/collections/{collection_id}/games/{game_id}/position": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Position */
    get: operations["position_api_collections__collection_id__games__game_id__position_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/collections/{collection_id}/games/{game_id}/analyses/{analysis_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Evidence */
    get: operations["evidence_api_collections__collection_id__games__game_id__analyses__analysis_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/learn/generation": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lesson */
    get: operations["lesson_api_learn_generation_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/learn/generation/sampling": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Sampling */
    get: operations["sampling_api_learn_generation_sampling_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/benchmarks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Benchmarks */
    get: operations["list_benchmarks_api_benchmarks_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/benchmarks/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Report */
    get: operations["report_api_benchmarks__id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/benchmarks/{id}/snapshots/{snapshot}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Saved Snapshot */
    get: operations["saved_snapshot_api_benchmarks__id__snapshots__snapshot__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/players": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Players */
    get: operations["players_api_players_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/new": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** New */
    post: operations["new_api_new_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/inspect": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Position */
    post: operations["position_api_inspect_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/apply": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Apply */
    post: operations["apply_api_apply_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/opponent": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Opponent */
    post: operations["opponent_api_opponent_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/play/controller/inspect": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Controller */
    post: operations["controller_api_play_controller_inspect_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/play/choose": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Play */
    post: operations["play_api_play_choose_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/play/session/inspect": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Session */
    post: operations["session_api_play_session_inspect_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ActorPolicy */
    ActorPolicy: {
      /**
       * Mode
       * @default plausible
       * @enum {string}
       */
      mode: "random" | "plausible" | "intervention";
      /**
       * Candidate Count
       * @default 3
       */
      candidate_count: number;
      /**
       * Max Cp Gap
       * @default 50
       */
      max_cp_gap: number;
      /**
       * Intervention Min Ply
       * @default 8
       */
      intervention_min_ply: number;
      /**
       * Intervention Max Ply
       * @default 80
       */
      intervention_max_ply: number;
      /**
       * Probability Rule
       * @default uniform-eligible-v1
       * @constant
       */
      probability_rule: "uniform-eligible-v1";
    };
    /** AnalysisPayload */
    AnalysisPayload: {
      /**
       * Version
       * @default 1
       * @constant
       */
      version: 1;
      answer?: components["schemas"]["TeacherAnalysis"] | null;
      /** Failure */
      failure?: string | null;
      /** Raw */
      raw?: string[];
      /** Candidates */
      candidates?: components["schemas"]["CandidateEvidence"][];
      /**
       * Coverage
       * @default unknown
       * @constant
       */
      coverage: "unknown";
    };
    /** ApplyRequest */
    ApplyRequest: {
      snapshot: components["schemas"]["Snapshot"];
      /** Move */
      move: string;
      /** Expected State Hash */
      expected_state_hash: string;
    };
    /** BenchmarkCatalog */
    BenchmarkCatalog: {
      /** Entries */
      entries?: components["schemas"]["BenchmarkEntry"][];
      /** Issues */
      issues?: string[];
    };
    /** BenchmarkEntry */
    BenchmarkEntry: {
      /** Id */
      id: string;
      /** Label */
      label: string;
      /** Series Id */
      series_id: string;
      /** Series Sha256 */
      series_sha256: string;
      /** Created At */
      created_at: string;
      /** Mode */
      mode: string;
      /** Book Use */
      book_use: string;
    };
    /** BenchmarkReport */
    BenchmarkReport: {
      summary: components["schemas"]["BenchmarkSummary"];
      /** Settings */
      settings: {
        [key: string]: {
          [key: string]: unknown;
        };
      };
      /** Book Provenance */
      book_provenance: string;
      /** Book Selection */
      book_selection: string;
      /** Snapshots */
      snapshots: string[];
    };
    /** BenchmarkSummary */
    BenchmarkSummary: {
      /**
       * Schema Version
       * @default 1
       * @constant
       */
      schema_version: 1;
      /** Series Id */
      series_id: string;
      /** Series Sha256 */
      series_sha256: string;
      /** Label */
      label: string;
      /** Spec Sha256 */
      spec_sha256: string;
      /** Evidence Sha256 */
      evidence_sha256: string;
      /** Created At */
      created_at: string;
      /**
       * Status
       * @enum {string}
       */
      status: "complete" | "incomplete" | "failed";
      /** Pool Status */
      pool_status: string;
      /** Results Hidden */
      results_hidden: boolean;
      /** Planned Games */
      planned_games: number;
      /** Completed Games */
      completed_games: number;
      /** Failed Attempts */
      failed_attempts: number;
      /** Interrupted Attempts */
      interrupted_attempts: number;
      /** Running Games */
      running_games: number;
      /** Reused Games */
      reused_games: number;
      /** Anchor */
      anchor: string;
      /** Entrants */
      entrants: {
        [key: string]: string;
      };
      fit?: components["schemas"]["RatingFit"] | null;
      /** Matchups */
      matchups?: components["schemas"]["Matchup"][];
      /** Costs */
      costs?: {
        [key: string]: components["schemas"]["Cost"];
      };
      /** Heldout Evidence */
      heldout_evidence: string;
      /** Notes */
      notes?: string[];
    };
    /** CandidateEvidence */
    CandidateEvidence: {
      /** Move */
      move: string;
      /** Depth */
      depth?: number | null;
      /**
       * Rank
       * @default 1
       */
      rank: number;
      score?: components["schemas"]["TeacherScore"] | null;
      /** Wdl */
      wdl?: number[] | null;
      /** Pv */
      pv: string[];
    };
    /** CatalogEntry */
    CatalogEntry: {
      /**
       * Schema Version
       * @default 1
       * @constant
       */
      schema_version: 1;
      /** Id */
      id: string;
      /** Title */
      title: string;
      /** Question */
      question: string;
      /**
       * Kind
       * @enum {string}
       */
      kind:
        | "teacher"
        | "learning"
        | "search"
        | "data"
        | "performance"
        | "other";
      /** Topics */
      topics: string[];
      /**
       * Execution
       * @enum {string}
       */
      execution:
        | "planned"
        | "running"
        | "complete"
        | "incomplete"
        | "failed"
        | "unknown";
      /**
       * Conclusion
       * @enum {string}
       */
      conclusion:
        | "unassessed"
        | "supported"
        | "not-supported"
        | "mixed"
        | "inconclusive";
      /**
       * Finding
       * @default
       */
      finding: string;
      /** Conditions */
      conditions: string;
      /**
       * Limitations
       * @default
       */
      limitations: string;
      /**
       * Decision
       * @default
       */
      decision: string;
      /**
       * Revisit
       * @default
       */
      revisit: string;
      /** Evidence */
      evidence?: components["schemas"]["EvidenceRef"][];
      /** Prior Work */
      prior_work?: components["schemas"]["PriorExperiment"][];
      /** Novelty */
      novelty: string;
      /** Owner */
      owner: string;
      /** Owner Sha256 */
      owner_sha256: string;
      /** Revision */
      revision: number;
      /** Evidence Locations */
      evidence_locations: components["schemas"]["EvidenceLocation"][];
    };
    /** CatalogIssue */
    CatalogIssue: {
      /** Owner */
      owner: string;
      /** Message */
      message: string;
    };
    /** Choice */
    Choice: {
      /** Move */
      move: string;
      /** State Hash */
      state_hash: string;
      /** Player Version */
      player_version: string;
      /** Seed */
      seed: number;
      /** Nodes */
      nodes: number;
      /** Completed Depth */
      completed_depth: number;
      /** Score */
      score: number | null;
      /** Elapsed Ms */
      elapsed_ms: number;
      /**
       * Qnodes
       * @default 0
       */
      qnodes: number;
      /**
       * Max Qply
       * @default 0
       */
      max_qply: number;
      /** Checkpoint Sha256 */
      checkpoint_sha256?: string | null;
      /**
       * Model Calls
       * @default 0
       */
      model_calls: number;
      mcts?: components["schemas"]["MctsStats"] | null;
      search_stats?: components["schemas"]["SearchStats"] | null;
      evaluation?: components["schemas"]["EvaluationBreakdown"] | null;
      engine?: components["schemas"]["EngineWork"] | null;
      /** Binding Sha256 */
      binding_sha256?: string | null;
    };
    /** CollectionCatalog */
    CollectionCatalog: {
      /** Collections */
      collections: components["schemas"]["CollectionEntry"][];
      /** Issues */
      issues: string[];
    };
    /** CollectionEntry */
    CollectionEntry: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Location */
      location: string;
      /** Bytes */
      bytes: number;
      /** Updated */
      updated: number;
    };
    /** CollectionPage */
    CollectionPage: {
      collection: components["schemas"]["CollectionEntry"];
      /** As Of */
      as_of: number;
      /** Runs */
      runs: components["schemas"]["GeneratedRun"][];
      overall: components["schemas"]["CollectionStats"];
      /** Run Stats */
      run_stats: {
        [key: string]: components["schemas"]["CollectionStats"];
      };
      filtered: components["schemas"]["CollectionStats"];
      /** Games */
      games: components["schemas"]["GeneratedGame"][];
      /** Total */
      total: number;
      /** Offset */
      offset: number;
      /** Limit */
      limit: number;
    };
    /** CollectionQuality */
    CollectionQuality: {
      /** As Of */
      as_of: number;
      /** Selected Occurrences */
      selected_occurrences: number;
      /** Unique Inputs */
      unique_inputs: number;
      /** Cross Split Inputs */
      cross_split_inputs: number;
      /** Affected Train */
      affected_train: number;
      /** Affected Validation */
      affected_validation: number;
      /** Phases */
      phases: {
        [key: string]: number;
      };
      /** Single Pv Budget Coverage */
      single_pv_budget_coverage: {
        [key: string]: number;
      };
      /** Specs */
      specs: components["schemas"]["SpecCoverage"][];
      /** Overlap Examples */
      overlap_examples: components["schemas"]["OverlapExample"][];
    };
    /** CollectionStats */
    CollectionStats: {
      /** Attempts */
      attempts: number;
      /** Accepted */
      accepted: number;
      /** Rejected */
      rejected: number;
      /** Other */
      other: number;
      /** Selected */
      selected: number;
      /** Shortfall Games */
      shortfall_games: number;
      /** Sampling Games */
      sampling_games: number;
      /** Unique Trajectories */
      unique_trajectories: number;
      /** Mean Plies */
      mean_plies: number | null;
      /** Policies */
      policies: {
        [key: string]: number;
      };
      /** Splits */
      splits: {
        [key: string]: number;
      };
      /** Outcomes */
      outcomes: {
        [key: string]: number;
      };
      /** Lengths */
      lengths: {
        [key: string]: number;
      };
      /** Actual */
      actual: {
        [key: string]: number;
      };
      /** Requested */
      requested: {
        [key: string]: number;
      };
    };
    /** ConfigurationChange */
    ConfigurationChange: {
      /** Ply */
      ply: number;
      controllers: components["schemas"]["Controllers"];
    };
    /**
     * Controller
     * @description A UI selection stores identity, never a resource path.
     */
    Controller: {
      /**
       * Player
       * @default human
       */
      player: string;
      /** Settings */
      settings?: {
        [key: string]: number;
      };
      /** Binding Sha256 */
      binding_sha256?: string | null;
      /** Checkpoint Sha256 */
      checkpoint_sha256?: string | null;
    };
    /** Controllers */
    Controllers: {
      red?: components["schemas"]["Controller"];
      black?: components["schemas"]["Controller"];
    };
    /** Corpus */
    Corpus: {
      /**
       * Schema Version
       * @default 1
       * @constant
       */
      schema_version: 1;
      /** Id */
      id: string;
      /**
       * Purpose
       * @default evaluation
       * @constant
       */
      purpose: "evaluation";
      /** Provenance */
      provenance: string;
      /** Openings */
      openings: components["schemas"]["Opening"][];
    };
    /** Cost */
    Cost: {
      /**
       * Decisions
       * @default 0
       */
      decisions: number;
      /**
       * Elapsed Ms
       * @default 0
       */
      elapsed_ms: number;
      /** Mean Move Ms */
      mean_move_ms?: number | null;
      /**
       * Qi Visits
       * @default 0
       */
      qi_visits: number;
      /**
       * Model Calls
       * @default 0
       */
      model_calls: number;
      /**
       * Engine Nodes
       * @default 0
       */
      engine_nodes: number;
      /**
       * Engine Decisions
       * @default 0
       */
      engine_decisions: number;
      /**
       * Engine Nodes Unknown
       * @default 0
       */
      engine_nodes_unknown: number;
    };
    /** EngineScore */
    EngineScore: {
      /**
       * Kind
       * @enum {string}
       */
      kind: "cp" | "mate";
      /** Value */
      value: number;
      /**
       * Bound
       * @enum {string}
       */
      bound: "exact" | "lowerbound" | "upperbound";
      /**
       * Perspective
       * @default side_to_move
       * @constant
       */
      perspective: "side_to_move";
    };
    /** EngineWork */
    EngineWork: {
      /** Engine Name */
      engine_name: string;
      /** Engine Sha256 */
      engine_sha256: string;
      /** Network Sha256 */
      network_sha256: string;
      /** Requested Nodes */
      requested_nodes: number;
      /** Requested Depth */
      requested_depth: number;
      /** Timeout Seconds */
      timeout_seconds: number;
      /** Reported Nodes */
      reported_nodes: number | null;
      /** Reported Depth */
      reported_depth: number | null;
      score: components["schemas"]["EngineScore"] | null;
      /** Threads */
      threads: number;
      /** Hash Mb */
      hash_mb: number;
      /**
       * Semantics
       * @default engine_native
       * @constant
       */
      semantics: "engine_native";
    };
    /** EvaluationBreakdown */
    EvaluationBreakdown: {
      /** Material */
      material: number;
      /** Placement */
      placement: number;
      /** Mobility */
      mobility: number;
      /** King Safety */
      king_safety: number;
    };
    /** EvidenceLocation */
    EvidenceLocation: {
      /** Path */
      path: string;
      /**
       * Role
       * @enum {string}
       */
      role: "report" | "results" | "config" | "data" | "source" | "run";
      /** Sha256 */
      sha256?: string | null;
      /** Available */
      available: boolean;
      /** Previewable */
      previewable: boolean;
    };
    /** EvidenceRef */
    EvidenceRef: {
      /** Path */
      path: string;
      /**
       * Role
       * @enum {string}
       */
      role: "report" | "results" | "config" | "data" | "source" | "run";
      /** Sha256 */
      sha256?: string | null;
    };
    /** ExperimentCatalog */
    ExperimentCatalog: {
      /** Entries */
      entries: components["schemas"]["CatalogEntry"][];
      /** Issues */
      issues: components["schemas"]["CatalogIssue"][];
      /**
       * Scope
       * @default Experiment entries in records/work-items/items and records/reports; unregistered work is not covered.
       */
      scope: string;
    };
    /** Frame */
    Frame: {
      /** Board */
      board: string;
      /**
       * Side
       * @enum {string}
       */
      side: "red" | "black";
    };
    /**
     * GameSession
     * @description Exploratory session evidence; validation does not resolve live resources.
     */
    GameSession: {
      /**
       * Format
       * @default qi-game-session
       * @constant
       */
      format: "qi-game-session";
      /**
       * Schema Version
       * @default 1
       * @constant
       */
      schema_version: 1;
      snapshot: components["schemas"]["Snapshot"];
      controllers: components["schemas"]["Controllers"];
      /**
       * Unknown Prefix
       * @default 0
       */
      unknown_prefix: number;
      /** Changes */
      changes: components["schemas"]["ConfigurationChange"][];
      /** History */
      history?: components["schemas"]["SessionMove"][];
    };
    /** GeneratedGame */
    GeneratedGame: {
      /** Id */
      id: number;
      /** Run Id */
      run_id: number;
      /** Attempt */
      attempt: string;
      /** Trajectory */
      trajectory: string;
      /** Source */
      source: string;
      /** Policy */
      policy: string;
      /** Split */
      split: string;
      /** Status */
      status: string;
      /** Disposition */
      disposition: string;
      /** Stop Reason */
      stop_reason: string | null;
      /** Outcome */
      outcome: string;
      /** Outcome Reason */
      outcome_reason: string | null;
      /** Plies */
      plies: number;
      /** Start Ply */
      start_ply: number;
      /** Selected */
      selected: number;
      /** Actual */
      actual: {
        [key: string]: number;
      };
      /** Requested */
      requested: {
        [key: string]: number;
      };
      /** Shortfall */
      shortfall: number;
      /** Updated */
      updated: number;
    };
    /** GeneratedGameDetail */
    GeneratedGameDetail: {
      game: components["schemas"]["GeneratedGame"];
      snapshot: components["schemas"]["Snapshot"];
      /** Initial Ply */
      initial_ply: number;
      /** Family */
      family: string;
      /** Failure */
      failure: string | null;
      /** Occurrences */
      occurrences: components["schemas"]["StoredOccurrence"][];
      /** Duplicate Games */
      duplicate_games: number[];
    };
    /** GeneratedRun */
    GeneratedRun: {
      /** Id */
      id: number;
      /** Identity */
      identity: string;
      /** Name */
      name: string;
      /** Status */
      status: string;
      /** Planned */
      planned: number;
      /** Continued From */
      continued_from: number | null;
      /** Created */
      created: number;
    };
    /** GenerationLesson */
    GenerationLesson: {
      example: components["schemas"]["LessonExample"];
      /** Phase Policy */
      phase_policy: string;
      /** Frames */
      frames: components["schemas"]["LessonFrame"][];
    };
    /** Glossary */
    Glossary: {
      /** Source */
      source: string;
      /** Glossary Sha256 */
      glossary_sha256: string;
      /** Entries */
      entries: components["schemas"]["GlossaryEntry"][];
    };
    /** GlossaryEntry */
    GlossaryEntry: {
      /** Term */
      term: string;
      /** Chinese */
      chinese: string;
      /** Meaning */
      meaning: string;
      /** Avoid */
      avoid: string;
      /** Category */
      category: string;
      /** Aliases */
      aliases: string[];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** InspectRequest */
    InspectRequest: {
      snapshot: components["schemas"]["Snapshot"];
    };
    /** LessonAnalysis */
    LessonAnalysis: {
      /** Ply */
      ply: number;
      /** Analysis Id */
      analysis_id: number;
      /** Nodes */
      nodes: number;
      /** Move */
      move: string;
      score: components["schemas"]["TeacherScore"];
      /** Spec Id */
      spec_id: string;
    };
    /** LessonBatch */
    LessonBatch: {
      /** Attempts */
      attempts: number;
      /** Accepted */
      accepted: number;
      /** Rejected */
      rejected: number;
      /** Endgame Shortfall Games */
      endgame_shortfall_games: number;
      /** Shared Inputs */
      shared_inputs: number;
      /** Observed At */
      observed_at: number;
    };
    /** LessonExample */
    LessonExample: {
      /** Collection */
      collection: string;
      /** Captured */
      captured: string;
      /** Game Id */
      game_id: number;
      /** Attempt */
      attempt: string;
      /** Trajectory */
      trajectory: string;
      snapshot: components["schemas"]["Snapshot"];
      actor: components["schemas"]["ActorPolicy"];
      /** Intervention Ply */
      intervention_ply: number;
      sampling_policy: components["schemas"]["SamplingPolicy"];
      sampling: components["schemas"]["SamplingResult"];
      /** Analyses */
      analyses: components["schemas"]["LessonAnalysis"][];
      /** Duplicate Games */
      duplicate_games: number[];
      batch: components["schemas"]["LessonBatch"];
    };
    /** LessonFrame */
    LessonFrame: {
      position: components["schemas"]["Position"];
      /**
       * Phase
       * @enum {string}
       */
      phase: "opening" | "middlegame" | "endgame" | "unknown";
      /** Mobile */
      mobile: number;
      /** Developed */
      developed: number;
    };
    /** MatchSummary */
    MatchSummary: {
      /**
       * Scorer
       * @default game-score-v1
       * @constant
       */
      scorer: "game-score-v1";
      /** Planned Pairs */
      planned_pairs: number;
      /** Completed Pairs */
      completed_pairs: number;
      /** Completed Games */
      completed_games: number;
      /** Failed Games */
      failed_games: number;
      /** Incomplete Games */
      incomplete_games: number;
      /** Unpaired Completed Games */
      unpaired_completed_games: number;
      /** Wins */
      wins: number;
      /** Draws */
      draws: number;
      /** Losses */
      losses: number;
      /** Score Rate */
      score_rate: number | null;
      /** Decisions */
      decisions: number;
      /** Mean Elapsed Ms */
      mean_elapsed_ms: number | null;
      /** A */
      a: string;
      /** B */
      b: string;
      /** Budget */
      budget: number;
      /** Pairs */
      pairs: number;
    };
    /** Matchup */
    Matchup: {
      /** A */
      a: string;
      /** B */
      b: string;
      /** Diagnostic */
      diagnostic: boolean;
      /**
       * Planned Pairs
       * @default 0
       */
      planned_pairs: number;
      /**
       * Completed Pairs
       * @default 0
       */
      completed_pairs: number;
      /**
       * Completed Games
       * @default 0
       */
      completed_games: number;
      /**
       * Failed Attempts
       * @default 0
       */
      failed_attempts: number;
      /**
       * Interrupted Attempts
       * @default 0
       */
      interrupted_attempts: number;
      /**
       * Reused Games
       * @default 0
       */
      reused_games: number;
      /**
       * Wins
       * @default 0
       */
      wins: number;
      /**
       * Draws
       * @default 0
       */
      draws: number;
      /**
       * Losses
       * @default 0
       */
      losses: number;
      /** Score Rate */
      score_rate?: number | null;
      /** Termination Reasons */
      termination_reasons?: {
        [key: string]: number;
      };
    };
    /** MctsStats */
    MctsStats: {
      /** Simulations */
      simulations: number;
      /** Tree Visits */
      tree_visits: number;
      /** Rollout Steps */
      rollout_steps: number;
      /** Terminal Simulations */
      terminal_simulations: number;
      /** Rollout Cutoffs */
      rollout_cutoffs: number;
      /** Budget Cutoffs */
      budget_cutoffs: number;
      /** Unfinished Simulations */
      unfinished_simulations: number;
      /** Max Tree Depth */
      max_tree_depth: number;
      /** Root Moves */
      root_moves: components["schemas"]["RootMove"][];
      /**
       * Leaf Nodes
       * @default 0
       */
      leaf_nodes: number;
      /**
       * Leaf Aborts
       * @default 0
       */
      leaf_aborts: number;
    };
    /** Opening */
    Opening: {
      /** Id */
      id: string;
      /** Description */
      description: string;
      snapshot: components["schemas"]["Snapshot"];
    };
    /** OpponentRequest */
    OpponentRequest: {
      snapshot: components["schemas"]["Snapshot"];
      /** Expected State Hash */
      expected_state_hash: string;
      /**
       * Player
       * @default alphabeta
       */
      player: string;
      /**
       * Seed
       * @default 0
       */
      seed: number;
      /**
       * Depth
       * @default 2
       */
      depth: number;
      /**
       * Nodes
       * @default 128
       */
      nodes: number;
      /**
       * Rollout Plies
       * @default 8
       */
      rollout_plies: number;
    };
    /** OpponentResult */
    OpponentResult: {
      position: components["schemas"]["Position"];
      choice: components["schemas"]["Choice"];
    };
    /** OverlapExample */
    OverlapExample: {
      /** Input Hash */
      input_hash: string;
      /** Train Occurrences */
      train_occurrences: number;
      /** Validation Occurrences */
      validation_occurrences: number;
      /** Train Game */
      train_game: number;
      /** Train Ply */
      train_ply: number;
      /** Validation Game */
      validation_game: number;
      /** Validation Ply */
      validation_ply: number;
    };
    /** Plan */
    Plan: {
      /**
       * Schema Version
       * @default 1
       * @constant
       */
      schema_version: 1;
      /** Name */
      name: string;
      /** Question */
      question: string;
      corpus: components["schemas"]["Corpus"];
      /** Players */
      players: string[];
      /** Budgets */
      budgets: number[];
      /** Seeds */
      seeds?: number[];
      /**
       * Depth
       * @default 3
       */
      depth: number;
      /**
       * Rollout Plies
       * @default 8
       */
      rollout_plies: number;
      /** Pairs */
      pairs?: [string, string][];
      /** Game Openings */
      game_openings?: string[];
      /** Winning Moves */
      winning_moves?: {
        [key: string]: string[];
      };
    };
    /** PlayRequest */
    PlayRequest: {
      snapshot: components["schemas"]["Snapshot"];
      /** Expected State Hash */
      expected_state_hash: string;
      controller: components["schemas"]["Controller"];
    };
    /** PlayResult */
    PlayResult: {
      position: components["schemas"]["Position"];
      choice: components["schemas"]["Choice"];
      config: components["schemas"]["PlayerConfig"];
    };
    /** PlayerConfig */
    PlayerConfig: {
      /**
       * Kind
       * @default alphabeta
       */
      kind: string;
      /**
       * Seed
       * @default 0
       */
      seed: number;
      /**
       * Depth
       * @default 2
       */
      depth: number;
      /**
       * Nodes
       * @default 128
       */
      nodes: number;
      /** Checkpoint Sha256 */
      checkpoint_sha256?: string | null;
      /**
       * Rollout Plies
       * @default 8
       */
      rollout_plies: number;
      /** Binding Sha256 */
      binding_sha256?: string | null;
      /**
       * Timeout Seconds
       * @default 10
       */
      timeout_seconds: number;
      /**
       * Work Semantics
       * @default qi
       * @enum {string}
       */
      work_semantics: "qi" | "engine_native";
    };
    /** PlayerInfo */
    PlayerInfo: {
      /** Id */
      id: string;
      /** Version */
      version: string;
      /** Label */
      label: string;
      /** Description */
      description: string;
      /** Uses Search */
      uses_search: boolean;
      /**
       * Default Nodes
       * @default 128
       */
      default_nodes: number;
      /**
       * Default Depth
       * @default 2
       */
      default_depth: number;
      /** Checkpoint Sha256 */
      checkpoint_sha256?: string | null;
      /** Default Rollout Plies */
      default_rollout_plies?: number | null;
      /**
       * Implementation Id
       * @default
       */
      implementation_id: string;
      /** Binding Sha256 */
      binding_sha256?: string | null;
      /**
       * Available
       * @default true
       */
      available: boolean;
      /** Unavailable Reason */
      unavailable_reason?: string | null;
      /** Settings */
      settings?: {
        [key: string]: components["schemas"]["Setting"];
      };
    };
    /** Position */
    Position: {
      snapshot: components["schemas"]["Snapshot"];
      /** Board */
      board: string;
      /**
       * Turn
       * @enum {string}
       */
      turn: "red" | "black";
      /** Ply */
      ply: number;
      /** State Hash */
      state_hash: string;
      /** Legal Moves */
      legal_moves: string[];
      /** In Check */
      in_check: boolean;
      outcome: components["schemas"]["Result"] | null;
    };
    /** PriorExperiment */
    PriorExperiment: {
      /** Id */
      id: string;
      /**
       * Relationship
       * @enum {string}
       */
      relationship: "extends" | "reproduces" | "challenges" | "uses";
      /** Contribution */
      contribution: string;
    };
    /** ProbeSummary */
    ProbeSummary: {
      /** Player */
      player: string;
      /** Budget */
      budget: number;
      /** Samples */
      samples: number;
      /** Expected */
      expected: number;
      /** Mean Ms */
      mean_ms: number;
      /** Mean Nodes */
      mean_nodes: number;
      /** Mean Depth */
      mean_depth: number;
      /** Tactical Solved */
      tactical_solved: number;
      /** Tactical Tested */
      tactical_tested: number;
      /** Mean Qnodes */
      mean_qnodes: number;
      /** Mean See Nodes */
      mean_see_nodes: number;
      /** Tt Hits */
      tt_hits: number;
      /** Tt Cutoffs */
      tt_cutoffs: number;
      /** Leaf Aborts */
      leaf_aborts: number;
    };
    /** Rating */
    Rating: {
      /** Entrant */
      entrant: string;
      /** Elo */
      elo?: number | null;
      /** Lower */
      lower?: number | null;
      /** Upper */
      upper?: number | null;
      /**
       * Games
       * @default 0
       */
      games: number;
      /**
       * Families
       * @default 0
       */
      families: number;
      /**
       * Interval Reason
       * @default No complete pairs connected to the anchor.
       */
      interval_reason: string;
    };
    /** RatingFit */
    RatingFit: {
      /**
       * Method
       * @default davidson-map-v1
       */
      method: string;
      /** Ratings */
      ratings: components["schemas"]["Rating"][];
      /** Red Advantage Elo */
      red_advantage_elo?: number | null;
      /** Draw Log Weight */
      draw_log_weight?: number | null;
      /**
       * Iterations
       * @default 0
       */
      iterations: number;
      /**
       * Bootstrap Successes
       * @default 0
       */
      bootstrap_successes: number;
      /**
       * Bootstrap Failures
       * @default 0
       */
      bootstrap_failures: number;
      /**
       * Interval Kind
       * @default 95% source-family cluster-bootstrap percentile interval of the regularized estimate
       */
      interval_kind: string;
    };
    /** RecordedTurn */
    RecordedTurn: {
      /** Ply */
      ply: number;
      /**
       * Side
       * @enum {string}
       */
      side: "red" | "black";
      choice: components["schemas"]["Choice"];
    };
    /** ReportBundle */
    ReportBundle: {
      data: components["schemas"]["ReportData"];
      /** Units */
      units: components["schemas"]["UnitDetail"][];
      /** Traces */
      traces: components["schemas"]["TraceBundle"][];
    };
    /** ReportData */
    ReportData: {
      /**
       * Schema Version
       * @default 1
       * @constant
       */
      schema_version: 1;
      /**
       * Kind
       * @default search
       * @constant
       */
      kind: "search";
      plan: components["schemas"]["Plan"];
      /** Provenance */
      provenance: {
        [key: string]: unknown;
      };
      /** Status */
      status: string;
      /** Completed */
      completed: number;
      /** Planned */
      planned: number;
      /** Validation */
      validation: string;
      /** Evidence Sha256 */
      evidence_sha256: string;
      /** Presentation Sha256 */
      presentation_sha256: string;
      glossary: components["schemas"]["Glossary"];
      summary: components["schemas"]["Summary"];
      /** By Position */
      by_position: {
        [key: string]: components["schemas"]["Summary"];
      };
      /** Units */
      units: components["schemas"]["UnitSummary"][];
      /** Traces */
      traces: components["schemas"]["TraceSummary"][];
      /** Warnings */
      warnings: string[];
      /** Narrative */
      narrative: string;
      /** Narrative Sha256 */
      narrative_sha256: string;
      /** Trace Unavailable Reason */
      trace_unavailable_reason: string | null;
    };
    /** Result */
    Result: {
      /** Winner */
      winner: ("red" | "black") | null;
      /** Reason */
      reason: string;
    };
    /** RootMove */
    RootMove: {
      /** Move */
      move: string;
      /** Visits */
      visits: number;
      /** Mean Value */
      mean_value: number | null;
    };
    /** RunEntry */
    RunEntry: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Location */
      location: string;
      /** Kind */
      kind: string;
      /** Status */
      status: string;
      /** Error */
      error?: string | null;
    };
    /** SamplingPolicy */
    SamplingPolicy: {
      /** Phase Counts */
      phase_counts?: {
        [key: string]: number;
      };
      /**
       * Min Spacing
       * @default 4
       */
      min_spacing: number;
      /**
       * Min Ply
       * @default 1
       */
      min_ply: number;
      /**
       * Max Ply
       * @default 299
       */
      max_ply: number;
      /**
       * Algorithm
       * @default seeded-greedy-phase-v1
       * @constant
       */
      algorithm: "seeded-greedy-phase-v1";
    };
    /** SamplingResult */
    SamplingResult: {
      /** Selected */
      selected: number[];
      /** Requested */
      requested: {
        [key: string]: number;
      };
      /** Actual */
      actual: {
        [key: string]: number;
      };
      /** Available */
      available: {
        [key: string]: number;
      };
      /** Shortfall */
      shortfall: {
        [key: string]: number;
      };
      /**
       * Excluded
       * @default 0
       */
      excluded: number;
      /**
       * Duplicates
       * @default 0
       */
      duplicates: number;
    };
    /** SearchStats */
    SearchStats: {
      /**
       * Cutoffs
       * @default 0
       */
      cutoffs: number;
      /**
       * See Nodes
       * @default 0
       */
      see_nodes: number;
      /**
       * Extensions
       * @default 0
       */
      extensions: number;
      /**
       * Max Extensions
       * @default 0
       */
      max_extensions: number;
      /**
       * Tt Hits
       * @default 0
       */
      tt_hits: number;
      /**
       * Tt Cutoffs
       * @default 0
       */
      tt_cutoffs: number;
    };
    /** SessionMove */
    SessionMove: {
      /** Ply */
      ply: number;
      /**
       * Side
       * @enum {string}
       */
      side: "red" | "black";
      controller: components["schemas"]["Controller"];
      config?: components["schemas"]["PlayerConfig"] | null;
      choice?: components["schemas"]["Choice"] | null;
    };
    /** SessionResult */
    SessionResult: {
      session: components["schemas"]["GameSession"];
      position: components["schemas"]["Position"];
    };
    /** Setting */
    Setting: {
      /** Label */
      label: string;
      /** Default */
      default: number;
      /** Minimum */
      minimum: number;
      /** Maximum */
      maximum: number;
      /**
       * Step
       * @default 1
       */
      step: number;
      /**
       * Unit
       * @default
       */
      unit: string;
    };
    /** Snapshot */
    Snapshot: {
      /**
       * Schema Version
       * @default 1
       * @constant
       */
      schema_version: 1;
      /**
       * Ruleset
       * @default xiangqi-training-v1
       * @constant
       */
      ruleset: "xiangqi-training-v1";
      /**
       * Initial Fen
       * @default rnbakabnr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RNBAKABNR w
       * @constant
       */
      initial_fen: "rnbakabnr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RNBAKABNR w";
      /** Moves */
      moves?: string[];
    };
    /** SpecCoverage */
    SpecCoverage: {
      /** Identity */
      identity: string;
      /** Nodes */
      nodes: number;
      /** Depth */
      depth: number | null;
      /** Multipv */
      multipv: number;
      /** Threads */
      threads: string;
      /** Engine */
      engine: string;
      /** Network */
      network: string;
      /** Occurrences */
      occurrences: number;
    };
    /** StoredAnalysis */
    StoredAnalysis: {
      /** Id */
      id: number;
      /** Spec Id */
      spec_id: string;
      /** Status */
      status: string;
      /** Resolved */
      resolved: boolean;
      /** Move */
      move: string | null;
      /** Nodes */
      nodes: number;
      /** Depth Limit */
      depth_limit: number | null;
      /** Multipv */
      multipv: number;
      /** Threads */
      threads: string;
      /** Engine */
      engine: string;
      /** Network */
      network: string;
      score: components["schemas"]["TeacherScore"] | null;
      /** Reported Depth */
      reported_depth: number | null;
      /** Reported Nodes */
      reported_nodes: number | null;
      /** Failure */
      failure: string | null;
    };
    /** StoredOccurrence */
    StoredOccurrence: {
      /** Id */
      id: number;
      /** Identity */
      identity: string;
      /** Ply */
      ply: number;
      /** Phase */
      phase: string;
      /** Selected */
      selected: boolean;
      /** Actor Move */
      actor_move: string | null;
      /** Intervention */
      intervention: boolean;
      /** Analyses */
      analyses: components["schemas"]["StoredAnalysis"][];
    };
    /** Summary */
    Summary: {
      /** Probes */
      probes: components["schemas"]["ProbeSummary"][];
      /** Matches */
      matches: components["schemas"]["MatchSummary"][];
      /** Unpaired Completed Games */
      unpaired_completed_games: number;
    };
    /** TeacherAnalysis */
    TeacherAnalysis: {
      /**
       * Schema Version
       * @default 1
       * @enum {integer}
       */
      schema_version: 1 | 2;
      /**
       * Adapter Version
       * @default uci-teacher-v1
       * @enum {string}
       */
      adapter_version: "uci-teacher-v1" | "uci-teacher-v2";
      snapshot: components["schemas"]["Snapshot"];
      /** State Hash */
      state_hash: string;
      /** Move */
      move: string;
      /** Engine Name */
      engine_name: string;
      /** Engine Sha256 */
      engine_sha256: string;
      /** Network Sha256 */
      network_sha256: string;
      /** Settings */
      settings: {
        [key: string]: string;
      };
      /** Requested Nodes */
      requested_nodes: number;
      /** Requested Depth */
      requested_depth: number | null;
      /** Timeout Seconds */
      timeout_seconds: number;
      /** Reported Nodes */
      reported_nodes: number | null;
      /** Reported Depth */
      reported_depth: number | null;
      score: components["schemas"]["TeacherScore"] | null;
      /** Elapsed Ms */
      elapsed_ms: number;
      /** Search Info */
      search_info: string[];
      /**
       * Invalid Actions
       * @default 0
       */
      invalid_actions: number;
      /**
       * Retries
       * @default 0
       */
      retries: number;
    };
    /** TeacherScore */
    TeacherScore: {
      /**
       * Kind
       * @enum {string}
       */
      kind: "cp" | "mate";
      /** Value */
      value: number;
      /**
       * Bound
       * @enum {string}
       */
      bound: "exact" | "lowerbound" | "upperbound";
      /**
       * Perspective
       * @default side_to_move
       * @constant
       */
      perspective: "side_to_move";
      /**
       * Semantics
       * @default engine_native
       * @constant
       */
      semantics: "engine_native";
    };
    /** TraceBundle */
    TraceBundle: {
      summary: components["schemas"]["TraceSummary"];
      /** Events */
      events: components["schemas"]["TraceEvent"][];
    };
    /** TraceEvent */
    TraceEvent: {
      /** Id */
      id: number;
      /** Parent */
      parent: number | null;
      /** Kind */
      kind: string;
      /** Board */
      board?: string | null;
      /** Side */
      side?: ("red" | "black") | null;
      /** Move */
      move?: string | null;
      /** Value */
      value?: number | null;
      /** Value Perspective */
      value_perspective?: string | null;
      /** Bound */
      bound?: string | null;
      /** Status */
      status?: string | null;
    } & {
      [key: string]: unknown;
    };
    /** TraceJob */
    TraceJob: {
      /** Id */
      id: string;
      request: components["schemas"]["TraceRequest"];
      /**
       * Status
       * @enum {string}
       */
      status:
        | "running"
        | "succeeded"
        | "failed"
        | "cancelled"
        | "timed-out"
        | "interrupted";
      /** Started */
      started: number;
      /** Finished */
      finished?: number | null;
      /** Message */
      message: string;
      /** Trace Id */
      trace_id?: string | null;
      /** Events */
      events?: number | null;
      /** Recording Complete */
      recording_complete?: boolean | null;
      /** Deadline Seconds */
      deadline_seconds: number;
    };
    /** TracePage */
    TracePage: {
      /** Events */
      events: components["schemas"]["TraceEvent"][];
      /** Total */
      total: number;
      /** Offset */
      offset: number;
    };
    /** TraceRequest */
    TraceRequest: {
      /** Run Id */
      run_id: string;
      /** Unit Id */
      unit_id: string;
      /** Unit Sha256 */
      unit_sha256: string;
      /** Turn Index */
      turn_index: number;
      /**
       * Limit
       * @default 100000
       */
      limit: number;
      /** Request Id */
      request_id: string;
    };
    /** TraceSummary */
    TraceSummary: {
      /** Id */
      id: string;
      /** Unit Id */
      unit_id: string;
      /** Turn Index */
      turn_index: number;
      /** Complete */
      complete: boolean;
      /** Events */
      events: number;
      /** Dropped Events */
      dropped_events: number;
      /** Event Limit */
      event_limit: number;
    };
    /** UnitDetail */
    UnitDetail: {
      job: components["schemas"]["UnitJob"];
      /** Status */
      status: string;
      /** Sha256 */
      sha256: string;
      /** Decisions */
      decisions: number;
      /** Frames */
      frames: components["schemas"]["Frame"][];
      /** Turns */
      turns: components["schemas"]["RecordedTurn"][];
      snapshot: components["schemas"]["Snapshot"];
    } & {
      [key: string]: unknown;
    };
    /** UnitJob */
    UnitJob: {
      /** Id */
      id: string;
      /**
       * Kind
       * @enum {string}
       */
      kind: "probe" | "game";
      /** Opening */
      opening: string;
      a: components["schemas"]["PlayerConfig"];
      b?: components["schemas"]["PlayerConfig"] | null;
      /** A Side */
      a_side?: ("red" | "black") | null;
    };
    /** UnitSummary */
    UnitSummary: {
      job: components["schemas"]["UnitJob"];
      /** Status */
      status: string;
      /** Sha256 */
      sha256: string;
      /** Decisions */
      decisions: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  reference_api_reference_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Glossary"];
        };
      };
    };
  };
  experiment_catalog_api_experiment_catalog_get: {
    parameters: {
      query?: {
        q?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExperimentCatalog"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  catalog_detail_api_experiment_catalog__experiment_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        experiment_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CatalogEntry"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  catalog_evidence_api_experiment_catalog__experiment_id__evidence__index__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        experiment_id: string;
        index: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  catalog_owner_api_experiment_catalog__experiment_id__owner_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        experiment_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  experiments_api_experiments_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunEntry"][];
        };
      };
    };
  };
  detail_api_experiments__run_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReportData"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  bundle_api_experiments__run_id__bundle_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReportBundle"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  unit_api_experiments__run_id__units__unit_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
        unit_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UnitDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  trace_api_experiments__run_id__traces__trace_id__get: {
    parameters: {
      query?: {
        parent?: number | null;
        offset?: number;
        limit?: number;
        view?: "all" | "mcts-tree";
        show_work?: boolean;
      };
      header?: never;
      path: {
        run_id: string;
        trace_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TracePage"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  export_api_experiments__run_id__export_get: {
    parameters: {
      query?: {
        format?: "html" | "md";
      };
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  evidence_api_experiments__run_id__evidence__reference__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
        reference: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  statuses_api_trace_jobs_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TraceJob"][];
        };
      };
    };
  };
  start_api_trace_jobs_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TraceRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TraceJob"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  cancel_api_trace_jobs__job_id__cancel_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TraceJob"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  collections_api_collections_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CollectionCatalog"];
        };
      };
    };
  };
  view_api_collections__collection_id__get: {
    parameters: {
      query?: {
        run?: number;
        policy?: string;
        split?: string;
        disposition?: string;
        outcome?: string;
        q?: string;
        phase?: "" | "opening" | "middlegame" | "endgame" | "unknown";
        lens?: "all" | "shortfall" | "long";
        sort?: "newest" | "longest" | "shortfall";
        offset?: number;
        limit?: number;
        attempts?: string;
      };
      header?: never;
      path: {
        collection_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CollectionPage"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  quality_api_collections__collection_id__quality_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        collection_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CollectionQuality"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  game_api_collections__collection_id__games__game_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        collection_id: string;
        game_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GeneratedGameDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  position_api_collections__collection_id__games__game_id__position_get: {
    parameters: {
      query?: {
        ply?: number;
      };
      header?: never;
      path: {
        collection_id: string;
        game_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Position"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  evidence_api_collections__collection_id__games__game_id__analyses__analysis_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        collection_id: string;
        game_id: number;
        analysis_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AnalysisPayload"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  lesson_api_learn_generation_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenerationLesson"];
        };
      };
    };
  };
  sampling_api_learn_generation_sampling_get: {
    parameters: {
      query?: {
        spacing?: number;
        seed?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SamplingResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_benchmarks_api_benchmarks_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BenchmarkCatalog"];
        };
      };
    };
  };
  report_api_benchmarks__id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BenchmarkReport"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  saved_snapshot_api_benchmarks__id__snapshots__snapshot__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
        snapshot: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BenchmarkSummary"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  players_api_players_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PlayerInfo"][];
        };
      };
    };
  };
  new_api_new_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Position"];
        };
      };
    };
  };
  position_api_inspect_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InspectRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Position"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  apply_api_apply_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ApplyRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Position"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  opponent_api_opponent_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OpponentRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OpponentResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  controller_api_play_controller_inspect_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Controller"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Controller"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  play_api_play_choose_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PlayRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PlayResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  session_api_play_session_inspect_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GameSession"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
